ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080

database:
  driverClassName: org.postgresql.Driver
  jdbcURL: ${DATABASE_URL:-jdbc:postgresql://localhost:5433/productdb}
  username: ${DATABASE_USER:-postgres}
  password: ${DATABASE_PASSWORD:-postgres}
  maximumPoolSize: 10
